version: '3.8'

services:
  ip-tracker-api:
    image: ip-tracker-api
    container_name: ip-tracker-api-container
    build:
      context: .
      target: $t
    environment: 
      - ASPNETCORE_URLS=http://+:80/
    restart: unless-stopped
    ports:
      - "64139:80"
    networks: 
      - backend

  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks: 
      - backend

networks: 
  backend:
    name: "backend"
    driver: "bridge"